/**
 * Quasar App Extension index/runner script
 * (runs on each dev/build)
 *
 * Docs: https://quasar.dev/app-extensions/development-guide/index-api
 */

/**
 * Take this as an example only.
 * We"ve cherry-picked just a few out of the many
 * things that you can do.
 */

import { defineIndexScript } from "@quasar/app-vite";

function extendQuasarConf (conf, api) {
  if (!conf.extras.includes("ionicons-v4")) {
    conf.extras.push("ionicons-v4");
  }

  conf.framework.iconSet = "ionicons-v4";
}

function onPublish (api, { arg, distDir }) {
  // this hook is called when "quasar build --publish" is called

  // your publish logic here...
  console.log("We should publish now. But maybe later? :)");

  // are we trying to publish a Cordova app?
  if (api.ctx.modeName === "cordova") {
    // do something
  }
}

function extendViteConf (viteConf, { isClient, isServer }, api) {
  // viteConf is the Vite config object generated by Quasar CLI
}

export default defineIndexScript((api) => {
  // (Optional!)
  // Quasar compatibility check; you may need
  // hard dependencies, as in a minimum version of the "quasar"
  // package or a minimum version of Quasar App CLI
  api.compatibleWith("quasar", "^2.0.0");
  api.compatibleWith("@quasar/app-vite", "^3.0.0-rc.1");

  // Here we extend /quasar.conf.js
  api.extendQuasarConf(extendQuasarConf);

  // Here we register the onPublish hook,
  // only if user answered that he wants the publishing service
  if (api.prompts.publishService) {
    api.onPublish(onPublish);
  }

  api.extendViteConf(extendViteConf);

  // there"s lots more hooks that you can use...
});
